### ISSUE TITLE
Pact Issues

### ISSUE THREAD

**Issue by jeffg2k** [StargateInvasion/SGI#1]
Pacts - there is a lot going on in the pacts, missing strings, unaligned brushes, and unknown abilities, but aside from those issues, the game crashes when a pact is accepted.

**Comment by dotNfg** [comment]
Basic missing strings for the Manage Pacts section have been restored. It's likely the bug (CTD when accepting a pact) was caused by missing files due to Google Drive issues but waiting for more confirmation. Strings still need to be cleaned (remove SGI named Pact research IDS string labels, link vanilla IDS labels to pact research entities and customize/transfer the Names and Descriptions for these strings).

**Comment by AceFighter** [comment]
Missing files were added in fix fdffaca6322b440666b9f188f9ee059921e5e062
