### ISSUE TITLE
asuran heros oberoth crash

### ISSUE THREAD

**Issue by jhuddle1** [StargateInvasion/SGI#101]
when I try to spawn oberoth the game is crashing dont know why ?

**Comment by jeffg2k** [comment]
Thanks for the report - we've reproduced the issue and will release a fix shortly.

**Comment by jeffg2k** [comment]
Fixed in https://github.com/StargateInvasion/SGI/commit/3fbdc7a48c0800347057faae5a43bd9eee4584c7 It was an issue with Titan abilities on a Capital ship.  Oberoth's city-ship is equivalent to a Titan, but Sins doesn't really like having more than 1 Titan, so we had to make it a Capital Ship.  But the abilities also have to be Capital Ship abilities or else it can cause issues (as you found out).  This probably won't be the final ability setup for Oberoth, but it fixes the issue until we can build some new ones.
