### ISSUE TITLE
Nemesis Mesh

### ISSUE THREAD

**Issue by AchillesBlade** [StargateInvasion/SGI#102]
Somewhere over the last month (possible the change on Feb 2) the meshes and icons for the Asuran's nemesis and long range corvettes got switched. The class titles are unchanged and the abilities still correlate with the titles so I believe it should be a simple fix to change the meshes and icons back.

**Comment by jeffg2k** [comment]
The change was intentional as in military terminology, the corvette is the smallest class of warship and smaller than a frigate.  The size and power of the models didn't make any sense as the corvette was larger and more powerful than most of the Asuran frigates.  Thus, the models and icons were switched to present the proper military nomenclature for ship scaling.

**Comment by AchillesBlade** [comment]
Okay, can we expect the abilities and stats to be transferred soon as well then?

**Comment by jeffg2k** [comment]
No, I think they're best how they are now.  The corvette should be the weaker, cheaper, faster ship. The corvette use to be much larger and weaker than all the other frigates (and many of the cruisers) and this made no sense, so they were essentially swapped and stats were adjusted.  A third ship, the light class, was also adjusted to provide proper scaling at the first three levels where cost, size, power, research increased with the type of ship.  I believe speed and armor was also adjusted to give the corvette more defense and maneuverability.  So if you want the old Nemesis, then the Erinyes Long Range frigate comes the closest to that build.
