### ISSUE TITLE
Negative Trinium & naquadah

### ISSUE THREAD

**Issue by noing92** [StargateInvasion/SGI#68]
While having a positive income on trinium and naquadah at 19% fleet upkeep

Negative income effect after researching crystal power systems or naquadah reactors in military research

**Comment by jeffg2k** [comment]
We'll keep a lookout for this and review the files.  What race were you playing?

SGI does have a unique upkeep system, so I'm not sure if this is a bug or feature.  It could be that you happened to build a bunch of ships during that timeframe.  It is possible to have negative income in SGI as it assigns a cost to each ship along with the overall fleet upkeep.  It's a hybrid system that hopes to make the cost of upkeep more linear.  Since ships have a specific upkeep cost, unlike the % based cost of fleet upkeep, it is possible to go negative - so make sure you can afford your fleet.

**Comment by jeffg2k** [comment]
It is possible to hit a negative if you build faster than you can support with the upkeep system. So, I'm going to close this for now as I don't yet see it as a bug.  If more information is gained and it appears it's outside the normal for what is expected, we can reopen.
