### ISSUE TITLE
Asgard Pulse Weapons

### ISSUE THREAD

**Issue by AceFighter** [StargateInvasion/SGI#9]
Many of the Tau’ri ships have Asgard Pulse Weapons. They should be called Asgard Plasma Weapons.

**Comment by jeffg2k** [comment]
Fixed in commit https://github.com/StargateInvasion/SGI/commit/d2933caba8060a58ef86bf02e6bd673cd42a3f96.  In the ship name, I changed it from Pulse Weapons to Plasma Weapons, since including Asgard would have the string length going over the gui edge.  For the research, I left it as Asgard Plasma Weapons as it fits fine.  It is likely possible to make the popup information window that displays such ship details wider if we do want to increase the length of these names.  If so, we can create a new issue for that task and then reopen this issue with an update.
